export const QuizListActions = {
    FETCH_QUZZES_START: 'FETCH_QUZZES_START',
    FETCH_RESP_DATA: 'FETCH_RESP_DATA',
    FETCH_ERROR_RESP: 'FETCH_RESP_ERROR'
}


export const QuizComponentActions = {
    START_FETCH_QUIZ: 'START_FETCH_QUIZ',
    QUIZ_RESP_DATA: 'QUIZ_RESP_DATA',
    QUIZ_FETCH_ERROR: 'QUIZ_FETCH_ERROR',


    // hadlers

    QUIZ_RESULT_ANSWER_STATE: 'QUIZ_RESULT_ANSWER_STATE',
    QUIZ_FINISH_QUIZ: 'QUIZ_FINISH_QUIZ',
    QUIZ_NEXT_QUESTION: 'QUIZ_NEXT_QUESTION',
    QUIZ_RETRY_BUTTON_CLICK: 'QUIZ_RETRY_BUTTON_CLICK'

}