export const QuizListActions = {
    FETCH_QUZZES_START: 'FETCH_QUZZES_START',
    FETCH_RESP_DATA: 'FETCH_RESP_DATA',
    FETCH_ERROR_RESP: 'FETCH_RESP_ERROR'
}


// Actions for Quiz Component 

export const quizComponent = {
    QUIZ_FETCH_DATA: 'QUIZ_FETCH_DATA',
    QUIZ_RESP_ERR: 'QUIZ_RESP_ERR',


    QUIZ_NEW_ANSWER_STATE: 'QUIZ_NEW_ANSWER_STATE',
    QUIZ_FINISH_QUIZ: 'QUIZ_FINISH_QUIZ',
    QUIZ_NEXT_QUESTION: 'QUIZ_NEXT_QUESTION',
    QUIZ_RETRY_QUIZ: 'QUIZ_RETRY_QUIZ'
}

// Quiz Creator Component 

export const QuizCreatorComponent = {
    CREATE_QUIZ_QUESTION: 'CREATE_QUIZ_QUESTION',
    CREATOR_QUIZ_READY: 'CREATOR_QUIZ_READY',
    CREATOR_RESET_DATA: 'CREATOR_RESET_DATA'
}


export const AuthComponent = {
    AUTH_SUCCESS_FETCH: 'AUTH_SUCCESS_FETCH',
    AUTH_LOGOUT: 'AUTH_LOGOUT'
}